### ISSUE TITLE
Opera Browser Detection not working

### ISSUE THREAD

**Issue by Angelo8828** [jenssegers/laravel-agent#27]
Hello, I am new in using this library and somehow, it is good. 

But in my testing, I discovered that it cannot detect Opera. It otherwise returned Google Chrome. When I looked in my database, the agent returned "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36 OPR/27.0.1689.76" and I guessed that the library reads the "Chrome" string and not the OPR. Please fix this issue.

Thanks.

**Comment by jenssegers** [comment]
Should be fixed now.

**Comment by Angelo8828** [comment]
Sorry for the late reply Sir.
It is still not working in my case. Here is the screenshot.

![git](https://cloud.githubusercontent.com/assets/11204084/6458089/40a0a660-c134-11e4-829a-0646c582b4fe.PNG)
